apiVersion: v1
kind: Namespace
metadata:
  name: dev-team
  labels:
    name: dev-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-app
  name: test-app
  namespace: dev-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: app
        env:
          - name: "SRV_PORT"
            value: "80"
          - name: "SERVER_NAME"
            value: "TEST-APP"

