apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-18
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-18"
---
