FROM amazon/aws-cli:2.13.24
#install tools
RUN  echo '[mongodb-org-4.4]'>/etc/yum.repos.d/mongodb-org-4.0.repo && \
     echo 'name=MongoDB Repository'>>/etc/yum.repos.d/mongodb-org-4.0.repo && \
     echo 'baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/'>>/etc/yum.repos.d/mongodb-org-4.0.repo && \
     echo 'gpgcheck=1'>>/etc/yum.repos.d/mongodb-org-4.0.repo && \
     echo 'enabled=1'>>/etc/yum.repos.d/mongodb-org-4.0.repo && \
     echo 'gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc'>>/etc/yum.repos.d/mongodb-org-4.0.repo  && \
     amazon-linux-extras install postgresql13 -y  && \
     yum install mongodb-org-tools mongodb-org-shell tar git  mysql  bind-utils bash-completion iputils  -y && \
     curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
     install skaffold /usr/local/bin/ && \
     rm -rf skaffold && \
     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
     chmod +x ./kubectl && \
     mv kubectl /usr/local/bin/kubectl && \
     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash && \
     helm plugin install https://github.com/jkroepke/helm-secrets --version v3.8.2 && \
     helm plugin install https://github.com/sstarcher/helm-release && \
     curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash && \
     echo 'source /usr/share/bash-completion/bash_completion'>>~/.bashrc && \
     echo 'source <(kubectl completion bash)'>>~/.bashrc && \
     echo 'complete -C "/usr/local/bin/aws_completer" aws'>>~/.bashrc && \
     echo 'source <(helm completion bash)'>>~/.bashrc && \
     echo 'source <(skaffold completion bash)'>>~/.bashrc && \
     yum clean all && \
     rm -rf /var/cache/yum

ENTRYPOINT ["/bin/bash"]
