apiVersion: v1
kind: Namespace
metadata:
  name: k8s-sync
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-svc-sync-kubeconfig
  namespace: k8s-sync
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
      name: local-cluster
    - cluster:
        certificate-authority-data: $CA_DATA
        server: $SERVER
      name: external-cluster
    contexts:
    - context:
        cluster: local-cluster
        user: local-cluster-user
      name: local-cluster
    - context:
        cluster: external-cluster
        user: external-cluster-user
      name: external-cluster
    current-context: local-cluster
    kind: Config
    preferences: {}
    users:
    - name: local-cluster-user
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: external-cluster-user
      user:
        token: $TOKEN
