---
apiVersion: v1
kind: Namespace
metadata:
  name: north
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
  namespace: north
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: public.ecr.aws/v8u2l1s7/vitdevops/cks-lab:cks_28_app1 # viktoruj/cks-lab:cks_28_app1
        name: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2
  namespace: north
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: public.ecr.aws/v8u2l1s7/vitdevops/cks-lab:cks_28_app2 # viktoruj/cks-lab:cks_28_app2 #
        name: app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app3
  name: app3
  namespace: north
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - image: public.ecr.aws/v8u2l1s7/vitdevops/cks-lab:cks_28_app3 # viktoruj/cks-lab:cks_28_app3
        name: app3
...