apiVersion: v1
kind: Namespace
metadata:
  name: team-purple
  labels:
    name: team-purple
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment1
  name: deployment1
  namespace: team-purple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment1
    spec:
      containers:
      - image: viktoruj/cks-lab
        name: busybox
        command: ['sh', '-c', 'while true ; do  echo "i am working ";  sleep 10  ;done']
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment2
  name: deployment2
  namespace: team-purple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment2
    spec:
      containers:
      - image: viktoruj/cks-lab
        name: busybox
        command: ['sh', '-c', 'while true ; do  echo "i am working ";  sleep 10  ;done']

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment3
  name: deployment3
  namespace: team-purple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment3
    spec:
      containers:
      - image: viktoruj/cks-lab
        name: busybox
        command: ['sh', '-c', 'while true ; do  echo "i am working ";  sleep 10  ;done']
