apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - command: ["while" , ":" "do", "sleep" , "1" , "done"  ]
    image: nginx
    name: nginx