apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cat
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cat
  name: cat
  namespace: cat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cat
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: cat
        env:
        - name: SERVER_NAME
          value: "cat-server"
        - name: SRV_PORT
          value: "80"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cat
  name: cat
  namespace: cat
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: cat
  type: ClusterIP

---
