apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: legacy
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: legacy-app
  name: legacy-app
  namespace: legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legacy-app
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: app1
        env:
        - name: SERVER_NAME
          value: "app1"
        - name: SRV_PORT
          value: "8081"
        - name: METRIC_PORT
          value: "9092"
        - name: LOG_PATH
          value: /log/logs1.txt
        - name: ENABLE_OUTPUT
          value: "false"
      - image: viktoruj/ping_pong
        name: app2
        env:
        - name: SERVER_NAME
          value: "app2"
        - name: SRV_PORT
          value: "8082"
        - name: METRIC_PORT
          value: "9092"
        - name: LOG_PATH
          value: /log/logs2.txt
        - name: ENABLE_OUTPUT
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: legacy-app
  name: legacy-app
  namespace: legacy
spec:
  ports:
  - name: http1app
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: metric1sapp
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: http2app
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: metrics2app
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: legacy-app
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: checker
  name: checker
  namespace: legacy
spec:
  containers:
  - image: viktoruj/cks-lab:latest
    name: checker
    command: ["sleep","60000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
