---
apiVersion: v1
kind: Namespace
metadata:
  name: swordfish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sword-app
  name: sword-app
  namespace: swordfish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sword-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sword-app
    spec:
      containers:
      - image: viktoruj/ping_pong:alpine
        name: app
        resources: {}
status: {}
