---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfish
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app1
  name: app1
  namespace: jellyfish
spec:
  containers:
  - image: viktoruj/ping_pong:alpine
    name: app
---
