apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: app-y
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: app1
  namespace: app-y
spec:
  containers:
  - env:
    - name: SERVER_NAME
      value: app-y
    image: viktoruj/ping_pong:alpine
    name: app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
