
---
apiVersion: v1
kind: Namespace
metadata:
  name: tuna
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-app
  name: web-app
  namespace: tuna
spec:
  containers:
  - image: viktoruj/ping_pong:alpine
    name: web-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-db
  name: mysql-db
  namespace: tuna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-db
    spec:
      containers:
      - image: viktoruj/ping_pong:alpine
        name: mysql-db
        env:
        - name: SERVER_NAME
          value: db-mysql
        - name: SRV_PORT
          value: "3306"
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-db
  name: mysql-db
  namespace: tuna
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-db
status:
  loadBalancer: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: tuna
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-app-db
  namespace: tuna
spec:
  podSelector:
    matchLabels:
      app: mysql-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tuna
      podSelector:
        matchLabels:
          type: backend
