---
apiVersion: v1
kind: Namespace
metadata:
  name: market
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
  namespace: market
spec:
  containers:
  - image: viktoruj/ping_pong:alpine
    name: market
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app
  namespace: market
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    run: app
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
  namespace: market
spec:
  containers:
    - image: viktoruj/ping_pong:alpine
      name: db
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: db
  name: db
  namespace: market
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    run: db
  type: ClusterIP
---
