apiVersion: v1
kind: Namespace
metadata:
  name: team-yellow
  labels:
    name: team-yellow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment1
  name: deployment1
  namespace: team-yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment1
    spec:
      containers:
      - image: viktoruj/cks-lab:cks_14_app1
        name: busybox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment2
  name: deployment2
  namespace: team-yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment2
    spec:
      containers:
      - image: viktoruj/cks-lab:cks_14_app2
        name: busybox