apiVersion: v1
kind: Namespace
metadata:
  name: team-5
  labels:
    name: team-5
---
apiVersion: v1
data:
  password: UGExNjM2d29yRA==
  user: YWQtYWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: db
  namespace: team-5
