apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prod-jobs
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: prod-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: ping-pong-cp6bg
        env:
        - name: ENABLE_LOAD_CPU
          value: "true"
        - name: CPU_MAXPROC
          value: "1"
        - name: CPU_USAGE_PROFILE
          value: '1=800=1=120 1=30=1=30'
        resources: {}
status: {}
