apiVersion: v1
kind: Namespace
metadata:
  name: team-red
  labels:
    name: team-red
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment1
  name: deployment1
  namespace: team-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment1
    spec:
      volumes:
        - name: host
          hostPath:
            # directory location on host
            path: /run/containerd
            # this field is optional
            type: Directory
            
      containers:
      - image: viktoruj/cks-lab
        name: busybox
        command: ['sh', '-c', 'while true ; do  echo "i am working ";  sleep 10  ;done']
        volumeMounts:
          - name: host
            mountPath: "/run/containerd"
            readOnly: false

