apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: dev-1
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
    team: finance
  name: pod1
  namespace: dev-1
spec:
  containers:
  - image: viktoruj/ping_pong:latest
    name: pod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
  namespace: dev-1
spec:
  containers:
  - image: viktoruj/ping_pong:latest
    name: pod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
  namespace: dev-1
spec:
  containers:
  - image: redis
    name: pod3
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod4
    team: finance
  name: pod4
  namespace: dev-1
spec:
  containers:
  - image: redis
    name: pod4
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod5
  name: pod5
  namespace: dev-1
spec:
  containers:
  - image: viktoruj/ping_pong:latest
    name: pod5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod6
    team: finance
  name: pod6
  namespace: dev-1
spec:
  containers:
  - image: viktoruj/ping_pong:latest
    name: pod6
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
