apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: db-redis
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-node
  name: redis-node
  namespace: db-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-node
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: redis-node
        resources: {}
status: {}
