apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: dev-2
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
  namespace: dev-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: ping-pong-n6tc8
        resources: {}
status: {}
