apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prod
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: viktoruj/ping_pong
        name: app
        env:
        - name: SERVER_NAME
          value: "ping-pong-server"
        - name: SRV_PORT
          value: "80"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: app
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-prom
  name: test-prom
  namespace: prod
spec:
  containers:
  - command:
    - sleep
    - "60000"
    image: viktoruj/cks-lab
    name: test-prom
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
