apiVersion: v1
kind: Namespace
metadata:
  name: rbac-1
  labels:
    name: rbac-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-2
  labels:
    name: rbac-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: dev
  namespace: rbac-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: dev
  namespace: rbac-1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: dev
  namespace: rbac-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev
subjects:
- kind: ServiceAccount
  name: dev
  namespace: rbac-1
---
apiVersion: v1
data:
  aaa: bbb
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-config
  namespace: rbac-2
