apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels:
    name: stage
---


# prod prod-db
apiVersion: v1
kind: Namespace
metadata:
  name: prod-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-index.html
  namespace: prod-db
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
    <head>
    <title>mysql </title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Welcome to mysql </h1>
    <p>If you see this page, the mysql mock  is working</p>

    </body>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
  namespace: prod-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      volumes:
      - name: index
        configMap:
          name: db-index.html
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: index
            mountPath: /usr/share/nginx/html/

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: prod-db
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: mysql

---
#all-pod
apiVersion: v1
kind: Namespace
metadata:
  name: user-client
  labels:
    name: user-client
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: all-pod-db-external
    role: db-external-connect
  name: all-pod-db-external
  namespace: user-client
spec:
  containers:
  - image: viktoruj/cks-lab
    command: ['sh', '-c', 'while true ; do  echo "$(date) i am working ";  sleep 10  ;done']
    name: all-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: all-pod
  name: all-pod
  namespace: user-client
spec:
  containers:
  - image: viktoruj/cks-lab
    command: ['sh', '-c', 'while true ; do  echo "$(date) i am working ";  sleep 10  ;done']
    name: all-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: all-stage-pod
  name: all-stage-pod
  namespace: stage
spec:
  containers:
  - image: viktoruj/cks-lab
    command: ['sh', '-c', 'while true ; do  echo "$(date) i am working ";  sleep 10  ;done']
    name: all-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-connect-stage-pod
    role: db-connect
  name: db-connect-stage-pod
  namespace: stage
spec:
  containers:
  - image: viktoruj/cks-lab
    command: ['sh', '-c', 'while true ; do  echo "$(date) i am working ";  sleep 10  ;done']
    name: all-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: prod-pod
  name: prod-pod
  namespace: prod
spec:
  containers:
  - image: viktoruj/cks-lab
    command: ['sh', '-c', 'while true ; do  echo "$(date) i am working ";  sleep 10  ;done']
    name: all-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
