---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: finance
  name: finance
  namespace: finance
spec:
  nodeSelector:
    work_type: app1
  containers:
  - image: viktoruj/ping_pong:alpine
    name: finance
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: finance
  name: finance
  namespace: finance
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: finance
  type: ClusterIP

---
apiVersion: v1
kind: Namespace
metadata:
  name: external
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: external
  name: external
  namespace: external
spec:
  nodeSelector:
    work_type: app2
  containers:
  - image: viktoruj/ping_pong:alpine
    name: external
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
