---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: finance
  name: finance
  namespace: finance
spec:
  containers:
  - image: viktoruj/ping_pong:alpine
    name: finance
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: external
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: external
  name: external
  namespace: external
spec:
  containers:
  - image: viktoruj/ping_pong:alpine
    name: external
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
