apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: eks-118
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: viktoruj/ping_pong:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demo-config
