apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: team-20
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: team20
  name: team20
  namespace: team-20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team20
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: team20
    spec:
      containers:
      - image: viktoruj/ping_pong:alpine
        name: app
        ports:
        - containerPort: 8080
