FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/mypackage/myapp/
COPY app/ .
RUN go mod tidy
RUN go build -ldflags="-w -s" -o app app.go

FROM --platform=linux/amd64 redis:7-bookworm AS redis-builder

FROM --platform=linux/amd64 amazon/aws-cli:2.34.37
COPY yum.repos /etc/yum.repos.d/
RUN yum install jq bc mariadb105 postgresql15 nc vim tar git wget make bind-utils iputils  -y  && \
    curl -LO https://dl.k8s.io/release/v1.36.0/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv kubectl /usr/local/bin/kubectl && \
    curl -Lo mongosh.tgz https://downloads.mongodb.com/compass/mongosh-2.5.0-linux-x64.tgz && \
    tar -xzf mongosh.tgz && \
    mv mongosh-2.5.0-linux-x64/bin/mongosh /usr/local/bin/mongosh && \
    rm -rf mongosh.tgz mongosh-2.5.0-linux-x64 && \
    curl -Lo atlas.tar.gz https://fastdl.mongodb.org/mongocli/mongodb-atlas-cli_1.24.0_linux_x86_64.tar.gz && \
    tar -xzf atlas.tar.gz && \
    mv mongodb-atlas-cli_1.24.0_linux_x86_64/bin/atlas /usr/local/bin/atlas && \
    rm -rf atlas.tar.gz mongodb-atlas-cli_1.24.0_linux_x86_64 && \
    curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.13.1-linux-amd64.tar.gz && \
    tar -zxvf helm.tar.gz && \
    rm -rf helm.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    helm plugin install https://github.com/jkroepke/helm-secrets && \
    curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
    chmod +x skaffold && \
    mv skaffold /usr/local/bin/skaffold && \
    skaffold version && \
    curl -Lo sops https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64 && \
    chmod +x sops && \
    mv sops /usr/local/bin/sops && \
    curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/master/install.sh | bash

COPY --from=builder /go/src/mypackage/myapp/app /app
COPY --from=redis-builder /usr/local/bin/redis-cli /usr/local/bin/redis-cli
COPY ./redis/redis_scan.sh /usr/local/bin/redis_scan
RUN chmod +x /usr/local/bin/redis_scan

COPY ./k8i/k8i.sh /usr/local/bin/k8i.sh
RUN echo 'source /usr/local/bin/k8i.sh' >> /root/.bashrc

ENTRYPOINT ["/app"]
