FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/mypackage/myapp/
COPY app/ .
RUN go mod tidy
RUN go build -ldflags="-w -s" -o app app.go

FROM amazon/aws-cli:2.15.47
COPY yum.repos /etc/yum.repos.d/
RUN yum install jq bc mongodb-atlas-cli mongodb-mongosh mysql postgresql netcat redis tar -y  && \
    curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/arm64/kubectl && \
    chmod +x ./kubectl && \
    mv kubectl /usr/local/bin/kubectl && \
    curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.15.1-linux-arm.tar.gz && \
    tar -zxvf helm.tar.gz && \
    mv linux-arm/helm /usr/local/bin/helm && \
    helm plugin install https://github.com/jkroepke/helm-secrets

#    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash && \
#    curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-arm64 && \
#    chmod +x skaffold && \
#    mv skaffold /usr/local/bin/skaffold && \
#    curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux && \
#    chmod +x sops && \
#    mv sops /usr/local/bin/sops && \
#    helm plugin install https://github.com/jkroepke/helm-secrets

COPY --from=builder /go/src/mypackage/myapp/app app
ENTRYPOINT ["/app"]