FROM ubuntu:24.04
#install tools
RUN atp update && apt install curl unzip  -y
#    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"  -o "awscliv2.zip" -s  && \
#    unzip awscliv2.zip >/dev/null && \
#    ./aws/install >/dev/null && \
#    aws --version && \
#    make --version
#

ENTRYPOINT ["/bin/bash"]
