FROM ubuntu:24.04
RUN apt update && apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt update && apt install -y curl unzip make git wget vim jq python3.11 python3.11-venv python3-pip pre-commit && \
    apt clean && rm -rf /var/lib/apt/lists/* && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" -s && \
    unzip awscliv2.zip >/dev/null && ./aws/install >/dev/null && \
    aws --version && make --version && rm awscliv2.zip && rm -rf aws && \
    wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.20/terragrunt_linux_arm64 && \
    chmod +x terragrunt_linux_arm64 && mv terragrunt_linux_arm64 /usr/bin/terragrunt && \
    terragrunt --version && \
    curl "https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_arm64.zip" -o "terraform.zip" -s && \
    unzip terraform.zip >/dev/null && chmod +x terraform && \
    mv terraform /usr/bin/ && rm terraform.zip && terraform --version && \
    ln -sf /usr/bin/python3 /usr/bin/python && ln -sf /usr/bin/pip3 /usr/bin/pip

ENTRYPOINT ["/bin/bash"]