FROM ubuntu:24.04
#install tools
RUN apt update && apt install curl unzip make git  -y && \
    apt  clean && rm -rf /var/lib/apt/lists/* && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"  -o "awscliv2.zip" -s  && \
    unzip awscliv2.zip >/dev/null && ./aws/install >/dev/null && \
    aws --version &&  make --version && rm awscliv2.zip && rm -rf aws

RUN curl "https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.8/terragrunt_linux_arm64"  -o "terragrunt" -s
RUN chmod +x terragrunt && mv terragrunt /usr/bin/
#RUN terragrunt --version

RUN  curl "https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_arm64.zip" -o "terraform.zip" -s
RUN  unzip terraform.zip >/dev/null && chmod +x terraform.zip
RUN  mv terraform /usr/bin/ && terraform --version
RUN  rm terraform.zip

ENTRYPOINT ["/bin/bash"]