FROM ubuntu:24.04
#install tools
RUN apt update && apt install curl unzip make git  -y && \
    apt  clean && rm -rf /var/lib/apt/lists/* && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"  -o "awscliv2.zip" -s && \
    unzip awscliv2.zip >/dev/null && ./aws/install >/dev/null && \
    aws --version &&  make --version && rm awscliv2.zip &&  rm -rf aws

RUN curl "https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.8/terragrunt_linux_amd64"  -o "terragrunt" -s  && \
    chmod +x terragrunt && mv terragrunt /usr/bin/ && \
    terragrunt --version

ENTRYPOINT ["/bin/bash"]
