apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: billing
  labels:
    name: billing
---
apiVersion: v1
data:
  aaa: bbb
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bill
  namespace: billing
---
apiVersion: v1
data:
  secret: MTExMTE=
kind: Secret
metadata:
  creationTimestamp: null
  name: db
  namespace: prod

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: k8api
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8api
  namespace: prod
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: k8api
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8api
subjects:
- kind: ServiceAccount
  name: k8api
  namespace: prod


---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment1
  name: deployment1
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment1
    spec:
      serviceAccountName: k8api
      containers:
      - image: viktoruj/cks-lab
        name: busybox
        command: ['sh', '-c', 'while true ; do  get_secret.sh ;  sleep 10  ;done']
        env:
          - name: NS
            value: "prod"
          - name: SECRET
            value: "db"
          - name: NS_CONFIGMAP
            value: "billing"
          - name: CONFIGMAP
            value: "bill"
